# Render deployment configuration
version: "1"

services:
  - type: web
    name: testlash-tizmi-backend
    runtime: node
    plan: free
    branch: main
    buildCommand: npm install --production
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: development
      - key: PORT
        value: "10001"
      - key: DATABASE_URL
        value: "postgresql://neondb_owner:npg_mDle56rIjyat@ep-small-sun-adywycce-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
      - key: JWT_SECRET
        value: "a46a32d07938ca1ade573dbfccfe253e29cfbf76092af8223327017370514d8eace56e6cc363d6"
      - key: IMAGEKIT_PUBLIC_KEY
        value: "public_/RQ7wDgI06wW6LhMZWzqITWrHz8="
      - key: IMAGEKIT_PRIVATE_KEY
        value: "private_2b0GeWBkCc0eMThbL6NaSyIKuhY="
      - key: IMAGEKIT_URL_ENDPOINT
        value: "https://ik.imagekit.io/your_imagekit_id"

databases:
  - name: testlash-tizmi-db
    plan: starter
    databaseName: testlash_tizmi
    user: testlash_user